### ISSUE TITLE
Quickstart guide

### ISSUE THREAD

**Issue by scott-mcnulty** [ericsakmar/connected-bike#1]
Do you mind publishing a quickstart guide for getting this up and running? Just got an ic4 the other week and this looks like the exact tool I've been looking for in terms of tracking

Thanks!

**Comment by ericsakmar** [comment]
For sure. I've got a few more bugs to clean up, but I'll get some deployment steps up shortly.

**Comment by ericsakmar** [comment]
Sorry for the delay! I just added some very basic dev/deployment notes to the readme. 

A big caveat to this whole project is that it's very specific to me, especially some of the calculations in `dataTransforms.js`. I'll slowly be working toward making it more configurable and universal as I have time, but I'd welcome PRs from others!
